# https://docs.docker.com/compose/compose-file/
version: '3.6'
services:
  grapevine:
    build: .
    depends_on:
      - postgres
    ports:
      - 4001:4001

  postgres:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: grapevine
      POSTGRES_PASSWORD: grapevine
      POSTGRES_USER: grapevine
    ports:
      - 15433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
