---

- name: copy epmd file
  copy:
    src: epmd
    dest: /home/deploy/
    mode: 0744
  become: yes
  become_user: deploy

- name: copy systemd file
  copy:
    src: epmd.service
    dest: /etc/systemd/system/epmd.service
  become: yes
  notify: reload systemd

- name: enable epmd service
  systemd:
    name: epmd.service
    enabled: yes
  become: yes
